In [ ]:
import pandas as pd

data = {
    "Car": [
        "Honda City",
        "Hyundai Creta",
        "Maruti Swift",
        "Tata Nexon",
        "Toyota Innova",
        "Honda Amaze",
        "Kia Seltos",
        "Maruti Baleno",
    ],
    "Company": [
        "Honda",
        "Hyundai",
        "Maruti",
        "Tata",
        "Toyota",
        "Honda",
        "Kia",
        "Maruti",
    ],
    "Year": [2022, 2023, 2021, 2023, 2022, 2020, 2024, 2021],
    "Price": [
        1200000,
        1500000,
        700000,
        1100000,
        2200000,
        650000,
        1600000,
        800000,
    ],
    "Mileage": [18, 17, 23, 19, 14, 20, 16, 22],
    "Fuel": [
        "Petrol",
        "Diesel",
        "Petrol",
        "Diesel",
        "Diesel",
        "Petrol",
        "Petrol",
        "Petrol",
    ],
    "Rating": [4.5, 4.3, 4.2, 4.4, 4.6, 4.0, 4.5, 4.1],
}

df = pd.DataFrame(data)

In [ ]:
df

             Car  Company  Year    Price  Mileage    Fuel  Rating
0     Honda City    Honda  2022  1200000       18  Petrol     4.5
1  Hyundai Creta  Hyundai  2023  1500000       17  Diesel     4.3
2   Maruti Swift   Maruti  2021   700000       23  Petrol     4.2
3     Tata Nexon     Tata  2023  1100000       19  Diesel     4.4
4  Toyota Innova   Toyota  2022  2200000       14  Diesel     4.6
5    Honda Amaze    Honda  2020   650000       20  Petrol     4.0
6     Kia Seltos      Kia  2024  1600000       16  Petrol     4.5
7  Maruti Baleno   Maruti  2021   800000       22  Petrol     4.1

In [5]:
df[["Car", "Price"]]

             Car    Price
0     Honda City  1200000
1  Hyundai Creta  1500000
2   Maruti Swift   700000
3     Tata Nexon  1100000
4  Toyota Innova  2200000
5    Honda Amaze   650000
6     Kia Seltos  1600000
7  Maruti Baleno   800000

In [6]:
#select.row.using.iloc
df.iloc[0:3]

             Car  Company  Year    Price  Mileage    Fuel  Rating
0     Honda City    Honda  2022  1200000       18  Petrol     4.5
1  Hyundai Creta  Hyundai  2023  1500000       17  Diesel     4.3
2   Maruti Swift   Maruti  2021   700000       23  Petrol     4.2

In [8]:
df.iloc[0:1]

          Car Company  Year    Price  Mileage    Fuel  Rating
0  Honda City   Honda  2022  1200000       18  Petrol     4.5

In [9]:
#filter cars based on price

expensive_cars = df[df["Price"]>1000000]

print(expensive_cars)

             Car  Company  Year    Price  Mileage    Fuel  Rating
0     Honda City    Honda  2022  1200000       18  Petrol     4.5
1  Hyundai Creta  Hyundai  2023  1500000       17  Diesel     4.3
3     Tata Nexon     Tata  2023  1100000       19  Diesel     4.4
4  Toyota Innova   Toyota  2022  2200000       14  Diesel     4.6
6     Kia Seltos      Kia  2024  1600000       16  Petrol     4.5

In [11]:
#sort car by price
sorted_cars = df.sort_values(by="Price")
print(sorted_cars)

             Car  Company  Year    Price  Mileage    Fuel  Rating
5    Honda Amaze    Honda  2020   650000       20  Petrol     4.0
2   Maruti Swift   Maruti  2021   700000       23  Petrol     4.2
7  Maruti Baleno   Maruti  2021   800000       22  Petrol     4.1
3     Tata Nexon     Tata  2023  1100000       19  Diesel     4.4
0     Honda City    Honda  2022  1200000       18  Petrol     4.5
1  Hyundai Creta  Hyundai  2023  1500000       17  Diesel     4.3
6     Kia Seltos      Kia  2024  1600000       16  Petrol     4.5
4  Toyota Innova   Toyota  2022  2200000       14  Diesel     4.6

In [12]:
from numpy import average
#calculate the average price

average_price = df["Price"].mean()
print(average_price)

1218750.0

In [13]:
#find the maximum and minimum price

print("higest price:",df["Price"].max())
print("lowest price:",df["Price"].min())

higest price: 2200000
lowest price: 650000

In [15]:
df.describe()

              Year         Price    Mileage    Rating
count     8.000000  8.000000e+00   8.000000  8.000000
mean   2022.000000  1.218750e+06  18.625000  4.325000
std       1.309307  5.304563e+05   3.020761  0.212132
min    2020.000000  6.500000e+05  14.000000  4.000000
25%    2021.000000  7.750000e+05  16.750000  4.175000
50%    2022.000000  1.150000e+06  18.500000  4.350000
75%    2023.000000  1.525000e+06  20.500000  4.500000
max    2024.000000  2.200000e+06  23.000000  4.600000

In [17]:
print(df["Company"].value_counts())

Company
Honda      2
Maruti     2
Hyundai    1
Tata       1
Toyota     1
Kia        1
Name: count, dtype: int64

In [19]:
# find unique fuel types

print(df["Fuel"].unique())

['Petrol' 'Diesel']

In [24]:
df.isnull().sum()

Car        0
Company    0
Year       0
Price      0
Mileage    0
Fuel       0
Rating     0
dtype: int64

In [25]:
sample = pd.DataFrame({
    "Car" : ["Honda","Tata","Maruti","Hyundai"],
    "Price" : [1200000,None,700000,1500000],
    "Mileage" : [18,23,None,17]
 })

print(sample)

       Car      Price  Mileage
0    Honda  1200000.0     18.0
1     Tata        NaN     23.0
2   Maruti   700000.0      NaN
3  Hyundai  1500000.0     17.0

In [26]:
sample['Price'] = sample['Price'].fillna(
    sample['Price'].mean()
)
sample['Mileage'] = sample['Mileage'].fillna(
    sample['Mileage'].mean()
)
print(sample)

       Car         Price    Mileage
0    Honda  1.200000e+06  18.000000
1     Tata  1.133333e+06  23.000000
2   Maruti  7.000000e+05  19.333333
3  Hyundai  1.500000e+06  17.000000

In [27]:
df = df.drop_duplicates()

df

             Car  Company  Year    Price  Mileage    Fuel  Rating
0     Honda City    Honda  2022  1200000       18  Petrol     4.5
1  Hyundai Creta  Hyundai  2023  1500000       17  Diesel     4.3
2   Maruti Swift   Maruti  2021   700000       23  Petrol     4.2
3     Tata Nexon     Tata  2023  1100000       19  Diesel     4.4
4  Toyota Innova   Toyota  2022  2200000       14  Diesel     4.6
5    Honda Amaze    Honda  2020   650000       20  Petrol     4.0
6     Kia Seltos      Kia  2024  1600000       16  Petrol     4.5
7  Maruti Baleno   Maruti  2021   800000       22  Petrol     4.1